/**
 * Every sentence the pages show, in one place, so the UI contract test can
 * read all of it. Plain words, sentence case, no semicolons or em dashes,
 * and nothing meant for developers.
 */

export const COPY = Object.freeze({
  // Shell
  serviceParent: "SoftQraft Cloud",
  serviceName: "Compute",
  fleetName: "Compute fleet",
  homeLabel: "SoftQraft Labs home",
  skip: "Skip to content",
  signOut: "Sign out",
  opening: "Opening Compute",
  signingIn: "Signing you in",

  // Signed out and expired links
  signedOutTitle: "Your session has ended",
  signedOutBody: "Open Compute again from SoftQraft to carry on.",
  signedOutAdminBody: "Open the fleet again from Ops to carry on.",
  launchFailedTitle: "This link has expired",
  launchFailedBody: "Open Compute again from SoftQraft. Each link works once.",
  openFromCloud: "Open from SoftQraft",
  openFromOps: "Open from Ops",
  signedOutNoLink: "Open Compute again from SoftQraft to carry on.",

  // Common
  retry: "Try again",
  cancel: "Cancel",
  close: "Close",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Select the text and copy it yourself.",
  loading: "Loading",
  back: "Back to VMs",
  actions: "Actions",

  // VM list
  vmsTitle: "Virtual machines",
  vmsLead: "Your VMs in this project.",
  createVm: "Create VM",
  emptyTitle: "No VMs yet",
  emptyBody: "A VM takes about a minute to start. You can connect with SSH as soon as it is running.",
  createFirstVm: "Create your first VM",
  colName: "Name",
  colStatus: "Status",
  colSize: "Size",
  colPrivateIp: "Private address",
  colCreated: "Created",
  colHost: "Host",
  noAddressYet: "Not yet",
  viewOnly: "View only",

  // Create
  createTitle: "Create a VM",
  createLead: "Pick a size and a key. Everything else is set up for you.",
  nameLabel: "Name",
  nameHint: "Lowercase letters, numbers and hyphens.",
  nameShuffle: "Suggest another name",
  nameInvalid: "Use lowercase letters, numbers and hyphens, starting with a letter.",
  sizeLabel: "Size",
  noSizes: "There is no room for a new VM right now. Delete a VM you no longer need, then try again.",
  imageLabel: "Operating system",
  keyLabel: "SSH key",
  keyHint: "Paste your public key. It is usually in the file ending in .pub in your .ssh folder.",
  keyPlaceholder: "ssh-ed25519 AAAA... you@laptop",
  keyAddAnother: "Use a different key",
  keyRemembered: "We remember this key for your next VM.",
  keyMissing: "Paste your SSH public key to continue.",
  createDefaults: "Private network only. No inbound traffic from the internet.",
  create: "Create",
  creating: "Creating",
  createdToast: "Your VM is starting.",

  // Detail
  detailConnect: "Connect",
  connectWhenRunning: "You can connect once the VM is running.",
  connectNoKey: "Use the SSH key you chose when you created this VM.",
  openConsole: "Open console",
  consoleReadyTitle: "Console ready",
  consoleReadyBody: "Your console session is ready and stays open for a short time.",
  detailAbout: "Details",
  factSize: "Size",
  factImage: "Operating system",
  factPrivateIp: "Private address",
  factCreated: "Created",
  usageTitle: "Usage so far",
  usageVcpu: "vCPU hours",
  usageMemory: "Memory GB hours",
  usageDisk: "Disk GB hours",
  usageUnavailable: "Usage is not available right now.",
  snapshotsTitle: "Snapshots",
  snapshotsEmpty: "No snapshots yet. Take one from the Actions menu.",
  deleteSnapshot: "Delete",
  waitingForRoom: "Waiting for room on a server. It starts as soon as there is space.",
  needsAttention: "Something went wrong with this VM. Try starting it again, or delete it.",
  gone: "This VM has been deleted.",

  // Actions menu
  start: "Start",
  stop: "Stop",
  resize: "Resize",
  resizeStopFirst: "Stop the VM to resize it",
  snapshot: "Take snapshot",
  snapshotNeedsState: "Available while the VM is running or stopped",
  deleteVm: "Delete VM",
  busy: "Wait until the VM has finished changing",
  startedToast: "Starting your VM.",
  stoppedToast: "Stopping your VM.",

  // Resize
  resizeTitle: "Resize VM",
  resizeBody: "Resizing works only while the VM is stopped. Start it again when the resize is done.",
  resizeSame: "Choose a size different from the current one.",
  resizeConfirm: "Resize",
  resizedToast: "Resizing your VM.",
  currentSize: "Current size",

  // Snapshot
  snapshotTitle: "Take a snapshot",
  snapshotBody: "A snapshot saves the disk as it is now.",
  snapshotNameLabel: "Snapshot name",
  snapshotNameInvalid: "Use lowercase letters, numbers and hyphens, starting with a letter. At most 40 characters.",
  snapshotConfirm: "Take snapshot",
  snapshotToast: "Saving a snapshot.",

  // Delete
  deleteTitle: "Delete this VM",
  deleteBody: "The VM, its disk and its snapshots are removed for good.",
  deleteSnapshotTitle: "Delete this snapshot",
  deleteSnapshotBody: "The snapshot is removed for good.",
  deleteTypeName: "Type the VM name to confirm",
  deleteConfirm: "Delete",
  deletedToast: "Deleting your VM.",
  snapshotDeletedToast: "Deleting the snapshot.",
  reauthTitle: "Sign in again to delete",
  reauthBody: "For your safety, deleting needs a sign-in from the last 15 minutes.",
  reauthAdminTitle: "Sign in again to make changes",
  reauthAdminBody: "For your safety, fleet changes need a sign-in from the last 15 minutes.",
  signInAgain: "Sign in again",

  // Fleet
  hostsTab: "Hosts",
  instancesTab: "All instances",
  hostsTitle: "Hosts",
  hostsLead: "The servers that run customer VMs.",
  addHost: "Add a host",
  hostsEmpty: "No hosts yet. Add a host to start running VMs.",
  colState: "State",
  colCapacity: "Capacity used",
  colFree: "Free",
  colLastSeen: "Last seen",
  never: "Never",
  drain: "Drain",
  disable: "Stop all VMs on this host",
  enable: "Enable",
  viewerReason: "View only. Your role can see the fleet but not change it.",
  drainedToast: "The host takes no new VMs.",
  disabledToast: "Stopping every VM on the host.",
  enabledToast: "The host is back in service.",
  disableTitle: "Stop all VMs on this host",
  disableBody: "Every running VM on this host stops now, and the host takes no new work until you enable it again.",
  disableConfirm: "Stop all VMs",
  enrolTitle: "Add a host",
  enrolBody: "Use this token once to enrol the new host. It is shown only now.",
  enrolExpires: "Works once. Expires in 30 minutes, at",
  enrolRunbook: "Open the runbook steps",
  enrolDone: "Done",
  instancesTitle: "All instances",
  instancesLead: "Every VM in every project, for support. Read only.",
  instancesEmpty: "No VMs yet.",
});
